const express = require('express');
const route = express.Router();
const authRoute = require('./authRoute');
const sourceRoute = require('./sourceRoute');
const connectionRoute = require('./connectionRoute');
const destinationRoute = require('./destinationRoute');
const connectorRoute = require("./connectorRoute");
const chatRoute = require("./chatRoute");
const categoryRoute = require("./categoryRoute");
const reportRoute = require("./reportRoute");
const suggestedQuestionRoute = require("./suggestedQuestionRoute");
const navigationRoute = require("./navigationRoutes");
const comapnyRoutes = require("./companyRoutes");
const webhooksRoute = require("./webhookRoutes");
const insightsRoute = require("./insightsRoute");
const adminRoute = require("./adminRoute");
const userCompaniesRoute = require("./userCompaniesRoute");
const mcpRoute = require("./mcpRoute");
route.use("/auth", authRoute);
route.use("/companies", userCompaniesRoute);
route.use("/source", sourceRoute);
route.use("/connection", connectionRoute);
route.use("/destination", destinationRoute);
route.use("/connector", connectorRoute);
route.use("/chat", chatRoute);
route.use("/category", categoryRoute);
route.use("/report", reportRoute);
route.use("/suggested-question", suggestedQuestionRoute);
route.use("/nav", navigationRoute);
route.use("/quick-dashboard", comapnyRoutes);
route.use("/insights", insightsRoute);
route.use("/admin",   adminRoute);
route.use("/webhook", webhooksRoute);
route.use("/mcp", mcpRoute);

module.exports = route;